#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const SOURCE_ROOTS = ["src"];
const EXTENSIONS = new Set([".js", ".jsx", ".ts", ".tsx"]);
const DEFAULT_MAX_LINES = 500;
const DEBT_GRACE_LINES = 25;

// Backend modules are still growing during the delivery push, so the backend
// pass uses a larger cap and a slightly larger grace. It exists to stop new
// 1000-line modules from appearing, not to force an immediate rewrite.
const BACKEND_SOURCE_ROOTS = ["nexus_backend/app"];
const BACKEND_EXTENSIONS = new Set([".py"]);
const BACKEND_DEFAULT_MAX_LINES = 700;
const BACKEND_DEBT_GRACE_LINES = 50;

// Baseline of backend modules already above the cap, generated by
// `node scripts/check_source_size.mjs --emit-backend-debt`. Values may only
// decrease; regenerate after a deliberate module split.
const BACKEND_DEBT_PATH = path.join(
  ROOT,
  "docs",
  "quality",
  "backend-source-size-baseline.json",
);
const BACKEND_MANAGED_DEBT = new Map(
  fs.existsSync(BACKEND_DEBT_PATH)
    ? Object.entries(
        JSON.parse(fs.readFileSync(BACKEND_DEBT_PATH, "utf8")).files || {},
      )
    : [],
);
// Deterministically generated, checked against the metadata snapshot in CI.
const GENERATED_FILES = new Set(['src/integrations/supabase/database-tables.ts']);

const IGNORED_DIRS = new Set([
  ".git",
  "coverage",
  "dist",
  "node_modules",
  "playwright-report",
  "test-results",
]);

const MANAGED_DEBT = new Map(
  Object.entries({
    "src/integrations/supabase/types.ts": 1298,
    "src/pages/OACenter.tsx": 1248,
    "src/pages/LLMModelManagement.tsx": 1052,
    "src/lib/animations.ts": 1168,
    "src/pages/crm/CustomerDetailSheet.tsx": 1126,
    "src/pages/OrgChartPage.tsx": 981,
    "src/pages/BattlecardLibrary.tsx": 933,
    "src/pages/AgentDebugPanel.tsx": 816,
    "src/pages/FinanceCenter.tsx": 803,
    "src/pages/SuperAdminDashboard.tsx": 797,
    "src/pages/AdminPanel.tsx": 788,
    "src/pages/ContractManagement.tsx": 768,
    "src/pages/TenderAnalysisPage.tsx": 761,
    "src/pages/TrainingCenter.tsx": 731,
    "src/components/ai/MessageBubble.tsx": 722,
    "src/pages/NotificationCenter.tsx": 678,
    "src/components/common/EnhancedNotificationCenter.tsx": 652,
    "src/pages/VMDTaskCenter.tsx": 568,
    "src/components/ui/sidebar.tsx": 638,
    "src/components/ai/chat/useChatPanel.ts": 629,
    "src/pages/HRCenter.tsx": 625,
    "src/components/projects/ProjectDetail.tsx": 622,
    "src/pages/VMDClueManagement.tsx": 620,
    "src/components/documents/DocumentsPage.tsx": 611,
    "src/components/approval/sections/BossApprovalView.tsx": 597,
    "src/components/common/DataExport.tsx": 591,
    "src/components/auth/LoginPage.tsx": 589,
    "src/components/settings/AISettingsPanel.tsx": 583,
    "src/pages/ProfileCenter.tsx": 582,
    "src/pages/AgentRunsPage.tsx": 573,
    "src/pages/AnimationShowcase.tsx": 569,
    "src/components/orgchart/OrgFlowCanvas.tsx": 557,
    "src/pages/InboxPage.tsx": 556,
    "src/components/workflow/WorkflowCanvas.tsx": 556,
    "src/pages/AIOperatingSystemPage.tsx": 546,
    "src/pages/AgentImprovementCenterPage.tsx": 533,
    "src/components/onboarding/OnboardingWizard.tsx": 527,
    "src/pages/ReportBuilderPage.tsx": 525,
    "src/pages/DataImportPage.tsx": 521,
    "src/hooks/useAIOperatingSystem.ts": 520,
    "src/pages/APIKeysPage.tsx": 515,
    "src/components/common/AnimatedComponents.tsx": 512,
    "src/components/forms/DynamicFormRenderer.tsx": 510,
    "src/components/forms/FormFieldEditor.tsx": 502,
  }),
);

function normalizePath(filePath) {
  return path.relative(ROOT, filePath).split(path.sep).join("/");
}

function walk(dir, files = [], extensions = EXTENSIONS) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (!IGNORED_DIRS.has(entry.name)) {
        walk(path.join(dir, entry.name), files, extensions);
      }
      continue;
    }
    if (entry.isFile() && extensions.has(path.extname(entry.name))) {
      files.push(path.join(dir, entry.name));
    }
  }
  return files;
}

function countLines(filePath) {
  const content = fs.readFileSync(filePath, "utf8");
  if (!content) return 0;
  return content.split(/\r\n|\r|\n/).length;
}

// `node scripts/check_source_size.mjs --emit-backend-debt` rewrites the backend
// baseline file after a deliberate module split.
if (process.argv.includes("--emit-backend-debt")) {
  const files = {};
  for (const sourceRoot of BACKEND_SOURCE_ROOTS) {
    const absoluteRoot = path.join(ROOT, sourceRoot);
    if (!fs.existsSync(absoluteRoot)) continue;
    for (const filePath of walk(absoluteRoot, [], BACKEND_EXTENSIONS)) {
      const lines = countLines(filePath);
      if (lines > BACKEND_DEFAULT_MAX_LINES) {
        files[normalizePath(filePath)] = lines;
      }
    }
  }
  const ordered = Object.fromEntries(
    Object.entries(files).sort((a, b) => a[0].localeCompare(b[0])),
  );
  fs.mkdirSync(path.dirname(BACKEND_DEBT_PATH), { recursive: true });
  fs.writeFileSync(
    BACKEND_DEBT_PATH,
    `${JSON.stringify(
      {
        generated_by: "scripts/check_source_size.mjs --emit-backend-debt",
        note: "Backend modules above the 700-line cap. Values may only decrease.",
        cap: BACKEND_DEFAULT_MAX_LINES,
        files: ordered,
      },
      null,
      2,
    )}\n`,
  );
  console.log(`BACKEND_SOURCE_SIZE_BASELINE_WRITTEN files=${Object.keys(ordered).length}`);
  process.exit(0);
}

const failures = [];
const warnings = [];

const sourceSets = [
  {
    roots: SOURCE_ROOTS,
    extensions: EXTENSIONS,
    defaultMaxLines: DEFAULT_MAX_LINES,
    grace: DEBT_GRACE_LINES,
    managedDebt: MANAGED_DEBT,
  },
  {
    roots: BACKEND_SOURCE_ROOTS,
    extensions: BACKEND_EXTENSIONS,
    defaultMaxLines: BACKEND_DEFAULT_MAX_LINES,
    grace: BACKEND_DEBT_GRACE_LINES,
    managedDebt: BACKEND_MANAGED_DEBT,
  },
];

for (const sourceSet of sourceSets) {
  for (const sourceRoot of sourceSet.roots) {
    const absoluteRoot = path.join(ROOT, sourceRoot);
    if (!fs.existsSync(absoluteRoot)) continue;

    for (const filePath of walk(absoluteRoot, [], sourceSet.extensions)) {
      const relativePath = normalizePath(filePath);
      if (GENERATED_FILES.has(relativePath)) continue;
      const lines = countLines(filePath);
      const debtBaseline = sourceSet.managedDebt.get(relativePath);

      if (debtBaseline !== undefined) {
        const allowed = debtBaseline + sourceSet.grace;
        if (lines > allowed) {
          failures.push(
            `${relativePath}: ${lines} lines exceeds managed-debt cap ${allowed}`,
          );
        } else if (lines > sourceSet.defaultMaxLines) {
          warnings.push(`${relativePath}: ${lines} lines tracked as managed debt`);
        }
        continue;
      }

      if (lines > sourceSet.defaultMaxLines) {
        failures.push(
          `${relativePath}: ${lines} lines exceeds ${sourceSet.defaultMaxLines}; split into focused modules`,
        );
      }
    }
  }
}

if (warnings.length) {
  console.log("Source size managed-debt warnings:");
  for (const warning of warnings) console.log(` - ${warning}`);
}

if (failures.length) {
  console.error("SOURCE_SIZE_GATE_FAIL");
  for (const failure of failures) console.error(` - ${failure}`);
  process.exit(1);
}

console.log("SOURCE_SIZE_GATE_OK");
