// Generated from read-only database metadata. Do not edit by hand.
// Run: python scripts/generate_supabase_contract.py
import type { Json } from './types';

// Column contract only: OpenAPI does not expose FK constraint names.
// Relation joins must use separately verified contracts or backend APIs.
type Table<Row, Required extends keyof Row> = {
  Row: Row;
  Insert: Pick<Row, Required> & Partial<Row>;
  Update: Partial<Row>;
  Relationships: [];
};

export type DatabaseTables = {
  users: Table<{
    id: string;
    name: string;
    role: "founder" | "sales" | "employee" | "manager" | "hr" | "boss" | "ai_assistant";
    department: string | null;
    avatar: string | null;
    score: number | null;
    rank: number | null;
    total_bonus: number | null;
    created_at: string | null;
    updated_at: string | null;
    manager_id: string | null;
    department_id: string | null;
    hire_date: string | null;
    title: string | null;
    org_id: string | null;
    organization_id: string | null;
    email: string | null;
    employee_number: string | null;
    job_title: string | null;
    approval_status: string;
  }, "name">;
  organizations: Table<{
    id: string;
    name: string;
    slug: string;
    plan: string | null;
    settings: Json | null;
    created_at: string | null;
    updated_at: string | null;
    invite_code: string | null;
    invite_code_enabled: boolean | null;
    invite_code_expires_at: string | null;
    brand: Json | null;
    stripe_customer_id: string | null;
    tier: string;
    payment_status: string | null;
  }, "name" | "slug">;
  sales_targets: Table<{
    id: string;
    organization_id: string;
    target_period: string;
    target_type: string;
    revenue_target: number | null;
    leads_target: number | null;
    conversions_target: number | null;
    win_rate_target: number | null;
    created_by: string | null;
    created_at: string | null;
    updated_at: string | null;
  }, "organization_id" | "target_period" | "target_type">;
  projects: Table<{
    id: string;
    user_id: string | null;
    name: string;
    type: string | null;
    stage: string | null;
    progress: number | null;
    description: string | null;
    metadata: Json | null;
    created_at: string | null;
    updated_at: string | null;
    organization_id: string | null;
    member_ids: Array<string> | null;
  }, "name">;
  sales_leads: Table<{
    id: string;
    user_id: string | null;
    name: string;
    company: string | null;
    title: string | null;
    score: number | null;
    stage: string;
    ai_suggestion: string | null;
    win_probability: number | null;
    last_contact: string | null;
    created_at: string | null;
    updated_at: string | null;
    organization_id: string | null;
    last_scored_at: string | null;
  }, "name">;
  ai_settings: Table<{
    id: string;
    user_id: string;
    base_url: string;
    api_key: string | null;
    model: string;
    created_at: string | null;
    updated_at: string | null;
    organization_id: string | null;
    behavior_preferences: Json | null;
    enabled_modules: Array<string> | null;
    maintenance_mode: boolean | null;
  }, "user_id" | "base_url" | "model">;
  sales_metrics: Table<{
    id: string;
    user_id: string;
    metric_type: string;
    value: number | null;
    metadata: Json | null;
    created_at: string | null;
    organization_id: string;
    date: string | null;
    leads_count: number | null;
    conversions: number | null;
    win_rate: number | null;
    revenue: number | null;
    calls_made: number | null;
    score: number | null;
  }, "user_id" | "metric_type" | "organization_id">;
  departments: Table<{
    id: string;
    name: string;
    description: string | null;
    parent_id: string | null;
    manager_id: string | null;
    budget_annual: number | null;
    cost_center: string | null;
    created_at: string | null;
    updated_at: string | null;
    organization_id: string | null;
    slug: string | null;
    sort_order: number | null;
    status: string | null;
  }, "name">;
  notifications: Table<{
    id: string;
    user_id: string;
    type: string;
    title: string;
    content: string;
    read: boolean | null;
    data: Json | null;
    created_at: string | null;
    organization_id: string | null;
    body: string | null;
    action_url: string | null;
    is_read: boolean | null;
  }, "user_id" | "type" | "title" | "content">;
  document_embeddings: Table<{
    id: number;
    content: string | null;
    metadata: Json | null;
    embedding: string | null;
    document_id: string | null;
    organization_id: string | null;
    chunk_index: number | null;
    content_hash: string | null;
    embedding_model: string | null;
    embedding_model_version: string | null;
    created_at: string | null;
    embedding_model_code: string | null;
    expires_at: string | null;
    parent_chunk_id: number | null;
    chunk_type: string;
    fts: string | null;
    access_groups: Array<string> | null;
    enriched_content: string | null;
  }, "id">;
  oa_tasks: Table<{
    id: string;
    title: string;
    description: string | null;
    assignee_id: string | null;
    created_by: string | null;
    project_id: string | null;
    status: string | null;
    priority: string | null;
    due_date: string | null;
    estimated_hours: number | null;
    actual_hours: number | null;
    ai_created: boolean | null;
    created_from_message_id: string | null;
    completed_at: string | null;
    created_at: string | null;
    updated_at: string | null;
    organization_id: string | null;
    completion_notes: string | null;
  }, "title">;
  finance_invoices: Table<{
    id: string;
    user_id: string | null;
    invoice_code: string | null;
    invoice_number: string | null;
    invoice_date: string | null;
    invoice_type: string | null;
    amount: number | null;
    tax_amount: number | null;
    total_amount: number | null;
    seller_name: string | null;
    seller_tax_id: string | null;
    image_url: string | null;
    ocr_data: Json | null;
    verified: boolean | null;
    verification_result: Json | null;
    used_in_claim_id: string | null;
    created_at: string | null;
    organization_id: string | null;
  }, never>;
  approval_requests: Table<{
    id: string;
    submitted_by: string;
    type: string;
    amount: number;
    description: string | null;
    status: string | null;
    chain_id: string | null;
    current_step: number | null;
    approval_level: string | null;
    escalated_at: string | null;
    escalation_reason: string | null;
    approved_by: string | null;
    approval_history: Json | null;
    on_behalf_of: string | null;
    submitted_via: string | null;
    submitted_at: string | null;
    created_at: string | null;
    ai_reason: string | null;
    rejection_reason: string | null;
    reviewed_by: string | null;
    reviewed_at: string | null;
    metadata: Json | null;
    org_id: string | null;
    organization_id: string;
    escalated: boolean | null;
    timeout_at: string | null;
    form_data: Json | null;
    form_schema_id: string | null;
    approval_comment: string | null;
    reject_to_step: number | null;
    resubmit_count: number | null;
  }, "submitted_by" | "type" | "amount" | "organization_id">;
  documents: Table<{
    id: string;
    name: string;
    doc_type: string | null;
    version: number | null;
    parent_id: string | null;
    extracted_data: Json | null;
    owner_id: string | null;
    department_id: string | null;
    created_at: string | null;
    status: string | null;
    progress: number | null;
    stage: string | null;
    visibility: string;
    department: string | null;
    org_id: string | null;
    organization_id: string | null;
    content_hash: string | null;
    error_log: string | null;
    category: string | null;
    embedding_model: string | null;
    embedding_model_version: string | null;
    updated_at: string | null;
    library_id: number | null;
    source_version: string | null;
    valid_until: string | null;
    review_status: string;
    reviewed_by: string | null;
    reviewed_at: string | null;
    indexed_at: string | null;
    quality_score: number | null;
    readiness_snapshot: Json;
    extraction_version: string | null;
    content_fingerprint: string | null;
    source_storage_path: string | null;
    source_content_type: string | null;
    ingestion_attempt: number;
    ingestion_updated_at: string | null;
    ingestion_error_code: string | null;
  }, "name" | "readiness_snapshot">;
  chat_messages: Table<{
    id: string;
    user_id: string;
    session_id: string;
    role: string;
    content: string;
    agent: string | null;
    metadata: Json | null;
    created_at: string | null;
    organization_id: string | null;
  }, "user_id" | "session_id" | "role" | "content">;
  project_timeline: Table<{
    id: string;
    project_id: string;
    title: string;
    content: string | null;
    status: string | null;
    event_type: string | null;
    created_at: string | null;
    occurred_at: string | null;
  }, "project_id" | "title">;
  oa_leave_requests: Table<{
    id: string;
    user_id: string | null;
    type: string;
    start_date: string;
    end_date: string;
    days: number;
    reason: string | null;
    handover_to: string | null;
    status: string | null;
    approval_level: string | null;
    approved_by: string | null;
    approved_at: string | null;
    approval_comment: string | null;
    ai_risk_score: number | null;
    created_at: string | null;
    updated_at: string | null;
    organization_id: string | null;
  }, "type" | "start_date" | "end_date" | "days">;
  oa_meeting_bookings: Table<{
    id: string;
    room_id: string | null;
    organizer_id: string | null;
    title: string;
    description: string | null;
    start_time: string;
    end_time: string;
    attendees: Array<string> | null;
    status: string | null;
    ai_generated: boolean | null;
    created_from: string | null;
    meeting_link: string | null;
    created_at: string | null;
    organization_id: string | null;
  }, "title" | "start_time" | "end_time">;
  hr_attendance: Table<{
    id: string;
    user_id: string | null;
    date: string;
    check_in: string | null;
    check_out: string | null;
    status: string | null;
    late_minutes: number | null;
    early_leave_minutes: number | null;
    overtime_hours: number | null;
    source: string | null;
    location: Json | null;
    created_at: string | null;
    organization_id: string | null;
  }, "date">;
  hr_salary_records: Table<{
    id: string;
    user_id: string | null;
    period: string;
    base_salary: number | null;
    performance_bonus: number | null;
    attendance_bonus: number | null;
    other_allowances: number | null;
    gross_salary: number | null;
    social_insurance: number | null;
    housing_fund: number | null;
    tax: number | null;
    other_deductions: number | null;
    net_salary: number | null;
    payment_date: string | null;
    payment_status: string | null;
    created_at: string | null;
    org_id: string | null;
    organization_id: string | null;
  }, "period">;
  hr_performance_reviews: Table<{
    id: string;
    user_id: string | null;
    reviewer_id: string | null;
    period: string;
    self_rating: number | null;
    manager_rating: number | null;
    final_rating: number | null;
    ai_rating: number | null;
    ai_analysis: string | null;
    goals: Json | null;
    strengths: string | null;
    improvements: string | null;
    status: string | null;
    submitted_at: string | null;
    reviewed_at: string | null;
    created_at: string | null;
    updated_at: string | null;
    org_id: string | null;
    organization_id: string | null;
  }, "period">;
  hr_job_positions: Table<{
    id: string;
    title: string;
    department: string | null;
    description: string | null;
    requirements: string | null;
    salary_range_min: number | null;
    salary_range_max: number | null;
    headcount: number | null;
    hired_count: number | null;
    status: string | null;
    created_by: string | null;
    created_at: string | null;
    updated_at: string | null;
    organization_id: string | null;
  }, "title">;
  hr_candidates: Table<{
    id: string;
    job_position_id: string | null;
    name: string;
    phone: string | null;
    email: string | null;
    resume_url: string | null;
    source: string | null;
    referrer_id: string | null;
    stage: string | null;
    rating: number | null;
    interview_notes: string | null;
    ai_analysis: Json | null;
    created_at: string | null;
    updated_at: string | null;
    organization_id: string | null;
  }, "name">;
  finance_budgets: Table<{
    id: string;
    department: string | null;
    project_id: string | null;
    category: string;
    year: number;
    month: number | null;
    planned_amount: number;
    used_amount: number | null;
    alert_threshold: number | null;
    created_at: string | null;
    updated_at: string | null;
    organization_id: string | null;
  }, "category" | "year" | "planned_amount">;
  contracts: Table<{
    id: string;
    organization_id: string;
    title: string;
    customer_id: string | null;
    contract_number: string | null;
    contract_type: string | null;
    status: string | null;
    amount: number | null;
    currency: string | null;
    start_date: string | null;
    end_date: string | null;
    signed_by: string | null;
    signed_at: string | null;
    document_url: string | null;
    tags: Array<string> | null;
    metadata: Json | null;
    created_at: string | null;
    updated_at: string | null;
  }, "organization_id" | "title">;
  audit_logs: Table<{
    id: string;
    action: string;
    actor_user_id: string | null;
    target_id: string | null;
    target_table: string | null;
    details_json: Json | null;
    ip_address: string | null;
    user_agent: string | null;
    session_id: string | null;
    request_id: string | null;
    status: string | null;
    error_message: string | null;
    timestamp: string | null;
    org_id: string | null;
    organization_id: string | null;
  }, "action">;
  dashboard_configs: Table<{
    id: string;
    user_id: string;
    organization_id: string | null;
    config_json: Json;
    created_at: string;
    updated_at: string;
  }, "user_id" | "config_json">;
  qa_pairs: Table<{
    id: string;
    question: string;
    answer: string;
    category: string | null;
    user_id: string;
    created_at: string;
    updated_at: string;
  }, "question" | "answer" | "user_id">;
  contract_events: Table<{
    id: string;
    contract_id: string;
    event_type: string;
    description: string | null;
    user_id: string | null;
    created_at: string | null;
  }, "contract_id" | "event_type">;
  customers: Table<{
    id: string;
    organization_id: string;
    name: string;
    company: string | null;
    industry: string | null;
    stage: string | null;
    source: string | null;
    estimated_value: number | null;
    assigned_to: string | null;
    tags: Array<string> | null;
    metadata: Json | null;
    created_at: string | null;
    updated_at: string | null;
    instrument_line_code: string | null;
    instrument_line_codes: Array<string>;
    application_fields: Array<string>;
    purchase_stage: string | null;
    budget_source: string | null;
    installed_base: Json;
    competitor_models: Array<string>;
  }, "organization_id" | "name" | "instrument_line_codes" | "application_fields" | "installed_base" | "competitor_models">;
  badges: Table<{
    id: string;
    user_id: string;
    name: string;
    icon: string | null;
  }, "user_id" | "name">;
  assets: Table<{
    id: string;
    organization_id: string;
    asset_code: string;
    name: string;
    asset_type: string;
    status: string | null;
    department_id: string | null;
    current_user_id: string | null;
    purchase_date: string | null;
    value: number | null;
    depreciation_rate: number | null;
    metadata: Json | null;
    created_at: string | null;
    updated_at: string | null;
  }, "organization_id" | "asset_code" | "name" | "asset_type">;
  certificates: Table<{
    id: string;
    organization_id: string;
    name: string;
    cert_type: string | null;
    holder_type: string | null;
    holder_id: string | null;
    cert_no: string | null;
    issue_date: string | null;
    expire_date: string | null;
    status: string | null;
    attachment_url: string | null;
    metadata: Json | null;
    created_at: string | null;
    updated_at: string | null;
  }, "organization_id" | "name">;
  user_scheduled_tasks: Table<{
    id: string;
    user_id: string;
    organization_id: string | null;
    name: string;
    prompt: string;
    schedule_type: string;
    hour: number | null;
    minute: number | null;
    day_of_week: number | null;
    interval_minutes: number | null;
    execute_at: string | null;
    is_active: boolean | null;
    last_executed_at: string | null;
    next_execution_at: string | null;
    execution_count: number | null;
    last_result: string | null;
    notify_method: string | null;
    created_at: string | null;
    updated_at: string | null;
    consecutive_failures: number | null;
    last_error: string | null;
    locked_by: string | null;
    locked_at: string | null;
    cron_expression: string | null;
  }, "user_id" | "name" | "prompt">;
};
